http:
  middlewares:
    xrealip-fixer:
      plugin:
        xrealip-fixer:
          autoRefresh: true
          refreshInterval: 30m
          directDepth: 1
          debug: true

  routers:
    whoami-router:
      rule: Host(`whoami.local`)
      entryPoints:
        - web
      service: whoami-svc
      middlewares:
        - xrealip-fixer

  services:
    whoami-svc:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
