http:
  middlewares:
    traefik-xrealip-fixer:
      plugin:
        traefik-xrealip-fixer:
          autoRefresh: true
          refreshInterval: 30m
          directDepth: 1
          debug: true

  routers:
    whoami1-router:
      rule: Host(`whoami1.local`)
      entryPoints:
        - web
      service: whoami1-svc
      middlewares:
        - traefik-xrealip-fixer
    whoami2-router:
      rule: Host(`whoami2.local`)
      entryPoints:
        - web
      service: whoami2-svc
      middlewares:
        - traefik-xrealip-fixer

  services:
    whoami1-svc:
      loadBalancer:
        servers:
          - url: "http://whoami1:80"
    whoami2-svc:
      loadBalancer:
        servers:
          - url: "http://whoami2:80"